// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    KAffix: typeof import('../packages/kbt-ui')['KAffix']
    KAlert: typeof import('../packages/kbt-ui')['KAlert']
    KAside: typeof import('../packages/kbt-ui')['KAside']
    KAutocomplete: typeof import('../packages/kbt-ui')['KAutocomplete']
    KAvatar: typeof import('../packages/kbt-ui')['KAvatar']
    KBacktop: typeof import('../packages/kbt-ui')['KBacktop']
    KBadge: typeof import('../packages/kbt-ui')['KBadge']
    KBreadcrumb: typeof import('../packages/kbt-ui')['KBreadcrumb']
    KBreadcrumbItem: typeof import('../packages/kbt-ui')['KBreadcrumbItem']
    KButton: typeof import('../packages/kbt-ui')['KButton']
    KButtonGroup: typeof import('../packages/kbt-ui')['KButtonGroup']
    KCalendar: typeof import('../packages/kbt-ui')['KCalendar']
    KCard: typeof import('../packages/kbt-ui')['KCard']
    KCarousel: typeof import('../packages/kbt-ui')['KCarousel']
    KCarouselItem: typeof import('../packages/kbt-ui')['KCarouselItem']
    KCascader: typeof import('../packages/kbt-ui')['KCascader']
    KCascaderPanel: typeof import('../packages/kbt-ui')['KCascaderPanel']
    KCheckbox: typeof import('../packages/kbt-ui')['KCheckbox']
    KCheckboxButton: typeof import('../packages/kbt-ui')['KCheckboxButton']
    KCheckboxGroup: typeof import('../packages/kbt-ui')['KCheckboxGroup']
    KCol: typeof import('../packages/kbt-ui')['KCol']
    KCollapse: typeof import('../packages/kbt-ui')['KCollapse']
    KCollapseItem: typeof import('../packages/kbt-ui')['KCollapseItem']
    KCollapseTransition: typeof import('../packages/kbt-ui')['KCollapseTransition']
    KColorPicker: typeof import('../packages/kbt-ui')['KColorPicker']
    KContainer: typeof import('../packages/kbt-ui')['KContainer']
    KConfigProvider: typeof import('../packages/kbt-ui')['KConfigProvider']
    KDatePicker: typeof import('../packages/kbt-ui')['KDatePicker']
    KDialog: typeof import('../packages/kbt-ui')['KDialog']
    KDivider: typeof import('../packages/kbt-ui')['KDivider']
    KDrawer: typeof import('../packages/kbt-ui')['KDrawer']
    KDropdown: typeof import('../packages/kbt-ui')['KDropdown']
    KDropdownItem: typeof import('../packages/kbt-ui')['KDropdownItem']
    KDropdownMenu: typeof import('../packages/kbt-ui')['KDropdownMenu']
    KEmpty: typeof import('../packages/kbt-ui')['KEmpty']
    KFooter: typeof import('../packages/kbt-ui')['KFooter']
    KForm: typeof import('../packages/kbt-ui')['KForm']
    KFormItem: typeof import('../packages/kbt-ui')['KFormItem']
    KHeader: typeof import('../packages/kbt-ui')['KHeader']
    KIcon: typeof import('../packages/kbt-ui')['KIcon']
    KImage: typeof import('../packages/kbt-ui')['KImage']
    KImageViewer: typeof import('../packages/kbt-ui')['KImageViewer']
    KInput: typeof import('../packages/kbt-ui')['KInput']
    KInputNumber: typeof import('../packages/kbt-ui')['KInputNumber']
    KLink: typeof import('../packages/kbt-ui')['KLink']
    KMain: typeof import('../packages/kbt-ui')['KMain']
    KMenu: typeof import('../packages/kbt-ui')['KMenu']
    KMenuItem: typeof import('../packages/kbt-ui')['KMenuItem']
    KMenuItemGroup: typeof import('../packages/kbt-ui')['KMenuItemGroup']
    KOption: typeof import('../packages/kbt-ui')['KOption']
    KOptionGroup: typeof import('../packages/kbt-ui')['KOptionGroup']
    KPageHeader: typeof import('../packages/kbt-ui')['KPageHeader']
    KPagination: typeof import('../packages/kbt-ui')['KPagination']
    KPopconfirm: typeof import('../packages/kbt-ui')['KPopconfirm']
    KPopper: typeof import('../packages/kbt-ui')['KPopper']
    KPopover: typeof import('../packages/kbt-ui')['KPopover']
    KProgress: typeof import('../packages/kbt-ui')['KProgress']
    KRadio: typeof import('../packages/kbt-ui')['KRadio']
    KRadioButton: typeof import('../packages/kbt-ui')['KRadioButton']
    KRadioGroup: typeof import('../packages/kbt-ui')['KRadioGroup']
    KRate: typeof import('../packages/kbt-ui')['KRate']
    KRow: typeof import('../packages/kbt-ui')['KRow']
    KScrollbar: typeof import('../packages/kbt-ui')['KScrollbar']
    KSelect: typeof import('../packages/kbt-ui')['KSelect']
    KSlider: typeof import('../packages/kbt-ui')['KSlider']
    KStep: typeof import('../packages/kbt-ui')['KStep']
    KSteps: typeof import('../packages/kbt-ui')['KSteps']
    KSubMenu: typeof import('../packages/kbt-ui')['KSubMenu']
    KSwitch: typeof import('../packages/kbt-ui')['KSwitch']
    KTabPane: typeof import('../packages/kbt-ui')['KTabPane']
    KTable: typeof import('../packages/kbt-ui')['KTable']
    KTableColumn: typeof import('../packages/kbt-ui')['KTableColumn']
    KTabs: typeof import('../packages/kbt-ui')['KTabs']
    KTag: typeof import('../packages/kbt-ui')['KTag']
    KText: typeof import('../packages/kbt-ui')['KText']
    KTimePicker: typeof import('../packages/kbt-ui')['KTimePicker']
    KTimeSelect: typeof import('../packages/kbt-ui')['KTimeSelect']
    KTimeline: typeof import('../packages/kbt-ui')['KTimeline']
    KTimelineItem: typeof import('../packages/kbt-ui')['KTimelineItem']
    KTooltip: typeof import('../packages/kbt-ui')['KTooltip']
    KTransfer: typeof import('../packages/kbt-ui')['KTransfer']
    KTree: typeof import('../packages/kbt-ui')['KTree']
    KTreeV2: typeof import('../packages/kbt-ui')['KTreeV2']
    KTreeSelect: typeof import('../packages/kbt-ui')['KTreeSelect']
    KUpload: typeof import('../packages/kbt-ui')['KUpload']
    KSpace: typeof import('../packages/kbt-ui')['KSpace']
    KSkeleton: typeof import('../packages/kbt-ui')['KSkeleton']
    KSkeletonItem: typeof import('../packages/kbt-ui')['KSkeletonItem']
    KStatistic: typeof import('../packages/kbt-ui')['KStatistic']
    KCheckTag: typeof import('../packages/kbt-ui')['KCheckTag']
    KDescriptions: typeof import('../packages/kbt-ui')['KDescriptions']
    KDescriptionsItem: typeof import('../packages/kbt-ui')['KDescriptionsItem']
    KResult: typeof import('../packages/kbt-ui')['KResult']
    KSelectV2: typeof import('../packages/kbt-ui')['KSelectV2']
    KWatermark: typeof import('../packages/kbt-ui')['KWatermark']
    KTour: typeof import('../packages/kbt-ui')['KTour']
    KTourStep: typeof import('../packages/kbt-ui')['KTourStep']
    KAnchor: typeof import('../packages/kbt-ui')['KAnchor']
    KAnchorLink: typeof import('../packages/kbt-ui')['KAnchorLink']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/kbt-ui')['KMessage']
    $notify: typeof import('../packages/kbt-ui')['KNotification']
    $msgbox: typeof import('../packages/kbt-ui')['KMessageBox']
    $messageBox: typeof import('../packages/kbt-ui')['KMessageBox']
    $alert: typeof import('../packages/kbt-ui')['KMessageBox']['alert']
    $confirm: typeof import('../packages/kbt-ui')['KMessageBox']['confirm']
    $prompt: typeof import('../packages/kbt-ui')['KMessageBox']['prompt']
    $loading: typeof import('../packages/kbt-ui')['KLoadingService']
  }
}

export {}
