export const PKG_PREFIX = '@kbt-ui'
export const PKG_NAME = 'kbt-ui'
export const PKG_CAMELCASE_NAME = 'KbtUI'
export const PKG_CAMELCASE_LOCAL_NAME = 'KbtUILocale'
export const PKG_BRAND_NAME = 'Kbt UI'
